---
# tasks file for wordpress
- name: download wordpress
  get_url:
      url=https://wordpress.org/latest.tar.gz
      dest=/tmp/wordpress.tar.gz
      validate_certs=no

- name: Unzip Wordpress tar file
  unarchive: 
        src=/tmp/wordpress.tar.gz 
        dest=/var/www/
        copy=no

- name: update default conf nginx site
  lineinfile:
      dest: /etc/nginx/sites-enabled/default
      regexp: "^\\s*root /var/www/html;$"
      line: "root /var/www/wordpress"
      insertafter: "^\\s*root /var/www/html;$"
      backrefs: yes
  notify:
      - restart nginx
- name: rename the smaple config file
  ansible.builtin.file:  
      src: /var/www/wordpress/wp-config-sample.php
      dest: /var/www/wordpress/wp-config.php
      state: link 
- name: update wordpress config file
  lineinfile:
       dest: /var/www/wordpress/wp-config.php
       regexp: "{{item.line}}"
       line: "{{ item.line }}"
  with_items:
       - {'regex': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('Db_name', '{{wp_mysql_db}}');"}
       - {'regex': "define\\('DB_USER', '(.)+'\\);", 'line': "define('Db_USER', '{{wp_mysql_user}}');"}
       - {'regex': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{wp_mysql_password}}');"}


